[package]
name = "moss"
version = "0.1.0"
edition = "2021"
authors = ["ekahPruthvi <ekahpdp@gmail.com>"]
description = "A Mossy dynamicLauncher"
license = "MIT"
repository = "https://github.com/ekahPruthvi/moss.git"

[dependencies]
fuzzy-matcher = "0.3.7"
glob = "0.3.2"
gtk4 = "0.9.6"
